name: Run npm cmd

on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string

jobs:
  setup_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Command
        run: npm run ${{ inputs.cmd }}
